name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM modules
      run: npm install

    - name: Replace the BackEnd endpoint
      run: echo "export const settings = {host:\"https://localhost:3030\"}" > src/config.js

    - name: Start Back-End
      run: npm run server-be &

    - name: Start Front-End
      run: npm run start-fe &

    - name: Install Browsers
      run: npx playwright install     
    
    - name: Start UI Tests
      run: npm run test-ui
